### ISSUE TITLE
About version

### ISSUE THREAD

**Issue by Cherry1024** [hizircanbayram/FeDQN-A-Federated-Learning-Approach-for-Training-Reinforcement-Learning-Agent-of-Atari-Games#1]
HI! Thanks for your wonderful work. I am a beginner and interested in your experiment. When I try to run the code, it shows that `gym.error.UnregisteredEnv: No registered env with id: PongDeterministic-v4`. So would you please tell me about your python and gym version?  Looking forward to your reply~ ;)

**Comment by hizircanbayram** [comment]
I'm sorry, I deleted its workspace. I don't remember its version. If you find, can you open a pull request? Thanks

**Comment by Cherry1024** [comment]
I finally find the reason. You should upgrade the gym to the newest version `pip install --upgrade gym`, `pip install gympip install -U gym`, `pip install gym[atari]`,  `pip install gym[accept-rom-license]`. It works for me😄
